import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Generated by: flutterfire configure (fill in values after Firebase Console setup)
/// Usage:  Firebase.initializeApp(options: DefaultFirebaseOptions.currentPlatform)
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) return web;
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions is not configured for this platform.',
        );
    }
  }

  // ── Web ──────────────────────────────────────────────────────────────────
  // Firebase Console → Project Settings → Your apps → Web app → Config
  static const FirebaseOptions web = FirebaseOptions(
    apiKey:            'REPLACE_WITH_WEB_API_KEY',
    appId:             'REPLACE_WITH_WEB_APP_ID',
    messagingSenderId: 'REPLACE_WITH_SENDER_ID',
    projectId:         'REPLACE_WITH_PROJECT_ID',
    storageBucket:     'REPLACE_WITH_PROJECT_ID.appspot.com',
    authDomain:        'REPLACE_WITH_PROJECT_ID.firebaseapp.com',
  );

  // ── Android ───────────────────────────────────────────────────────────────
  // Values from android/app/google-services.json
  static const FirebaseOptions android = FirebaseOptions(
    apiKey:            'AIzaSyBsqcxYnoQ6DIF-I3HgoEqZEIWePh-VdEo',
    appId:             '1:974664651910:android:3a38f124b1f8cdec05ad07',
    messagingSenderId: '974664651910',
    projectId:         'mfu-dormitory-e11c0',
    storageBucket:     'mfu-dormitory-e11c0.firebasestorage.app',
  );

  // ── iOS ───────────────────────────────────────────────────────────────────
  // Values from ios/Runner/GoogleService-Info.plist
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey:            'AIzaSyAMazz81BxZkmM1ZZGIV_p5YC6BIPEuuIs',
    appId:             '1:974664651910:ios:d9943abc84ff34ad05ad07',
    messagingSenderId: '974664651910',
    projectId:         'mfu-dormitory-e11c0',
    storageBucket:     'mfu-dormitory-e11c0.firebasestorage.app',
    iosBundleId:       'com.example.studentAccessApp',
  );
}
